// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf_azDXM69RG_ryRAaHJrgooVq3UX_K4U',
    appId: '1:493629751703:web:bc61fa8061fa20ba17c4d2',
    messagingSenderId: '493629751703',
    projectId: 'chotu-admin-app',
    authDomain: 'chotu-admin-app.firebaseapp.com',
    storageBucket: 'chotu-admin-app.firebasestorage.app',
    measurementId: 'G-EYKW61YSSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmh2Zi847mYTX9c2PkSXmEmdpE7XIq1yk',
    appId: '1:493629751703:android:c0ffa5635014361617c4d2',
    messagingSenderId: '493629751703',
    projectId: 'chotu-admin-app',
    storageBucket: 'chotu-admin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLxDP8AwNjJSF5ryKUgnEOw-8JPzsjrv0',
    appId: '1:493629751703:ios:325a58f6c908d54a17c4d2',
    messagingSenderId: '493629751703',
    projectId: 'chotu-admin-app',
    storageBucket: 'chotu-admin-app.firebasestorage.app',
    iosBundleId: 'com.example.chotuAdmin',
  );
}
